config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  root to:'home#index'
  get 'home/about', to: 'home#about', as: 'home_about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   belongs_to :user
    
   validates :title, presence: true
   validates :body, length: { minimum: 1, maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name,uniqueness: true
  validates :email,presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  
  def email_required?
  	false
  end

  def email_changed?
  	false
  end

  has_many :books, dependent: :destroy

  attachment :profile_image


  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_action :configure_permitted_parameters, if: :devise_controller?
 protect_from_forgery with: :exception

 protected
 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
 end

 def after_sign_in_path_for(resource)
	 user_path(current_user.id)
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create,:edit,:update,:destroy,:index, :show]
    
    def new
        @book = Book.new
        @books = Book.all
    end

    def index
        @books = Book.all
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
            flash[:notice] = "You have creatad book successfully."
            redirect_to @book
        else
            @books = Book.all
            render 'index'
        end
    end

    def show
        @book = Book.find(params[:id])
        @user = User.find(@book.user.id)
        @books = Book.new
    end

    def edit
        @book = Book.find(params[:id])
        if @book.user_id == current_user.id
            flash[:edit] = "successfully edit"
        else
            redirect_to books_path
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
          redirect_to @book
        else
          render 'edit'
        end
    end

    private
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only:[:show, :index, :edit, :update, :destroy]

  def show
  	@user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
  end

  def index
  	@users = User.all
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def destroy
    flash[:notice] = 'successfully log out'
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1>Editing Book</h1>
            <%= form_for(@book) do |f| %>
            <% if @book.errors.any? %>
            <div id="error_explanation">
            <h2 style="font-size:24px; color:red;"><%= pluralize(@book.errors.count, "error" )%>  prohibited this obj from being saved:</h2>
                    <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li style="font-size:13px; color:red;"><%= message %></li>
                <% end %>
                    </ul>
            </div>
            <% end %>
            <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Title</h4>
                <%= f.text_field :title, class:"book_title col-xs-12" %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Opinion</h4>
                <%= f.text_area :body, class:"book_body col-xs-12"  %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <%= f.submit "Update Book", class:"book_submit btn btn-primary col-xs-12" %>
                </div>
            <% end %>
                <%= link_to "show" , book_path(@book.id), class:"book_#{@book.id}" %> | <%= link_to "Back", books_path, class:"back" %>
    </div>
    </div>
        <div class="row">
    <div class="col-xs-3 col-xs-offset-9" style="margin-left:75%;">
      <p style="font-size:13px;">CopyRight Infratop.inc</p>
    </div>
</div>

app/views/books/index.html.erb
<div class="container">
　　　　　　　<%= form_for(@book) do |f| %>
            <% if @book.errors.any? %>
            <div id="error_explanation">
            <h2 style="font-size:24px; color:red;"><%= pluralize(@book.errors.count, "error" )%>  prohibited this obj from being saved:</h2>
                    <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li style="font-size:13px; color:red;"><%= message %></li>
                <% end %>
                    </ul>
            </div>
            <% end %>
    <div class="row">
        <div class="col-xs-3">
            <h2>User info</h2>
                <table class="table">
                    <tr>
                    <%= attachment_image_tag current_user, :profile_image, format:'jpeg', class: " pull-left profile-thumb", size: "100x100", fallback: "no_image.png"%>
                    </tr>
                    <tr>
                        <th>name</th>
                        <th><%= current_user.name %></th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th><%= current_user.introduction %></th>
                    </tr>
                </table>
            <div class="row">
            <% if current_user.id %>
             <p><%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{current_user.id}" %></p>
            <% end %>
            </div>
                <h2>New book</h2>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Title</h4>
                <%= f.text_field :title, class:"book_title col-xs-12" %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Opinion</h4>
                <%= f.text_area :body, class:"book_body col-xs-12"  %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <%= f.submit "Create Book", class:"book_submit btn btn-primary col-xs-12" %>
                </div>
        <% end %>   
        </div>


        <div class="col-xs-9">
            <h2>Books </h2>
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                    </tr>
                </thead>
                <% @books.each do |book| %>
                <thead>
                    <tr>
                        <th><%= attachment_image_tag book.user, :profile_image, format:'jpeg', class: " pull-left profile-thumb", size: "50x50", fallback: "no_image.png"%></th>
                        <th>
                        <%= link_to book_path(book.id), class:"book_#{book.id}" do %>
                        <%= book.title %>
                        <% end %>
                        </th>
                        <th><%= book.body %></th>
                    </tr>
                </thead>
                <% end %>
            </table>
        </div>
    </div>
    <div class="row">
    <div class="col-xs-3 col-xs-offset-9" style="margin-left:75%;">
      <p style="font-size:13px;">CopyRight Infratop.inc</p>
    </div>
  </div>
</div>

app/views/books/new.html.erb
    <div class="row">
        <div class="col-xs-3">
        <%= form_for(@book, url: books_path) do |f| %>
            <% if @book.errors.any? %>
            <div id="error_explanation">
            <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
                    <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <li><%= message %></li>
                <% end %>
                    </ul>
            </div>
            <% end %>
        <div>
            <h2>User info</h2>
                <table class="table">
                    <tr><%= attachment_image_tag @user, :profile_image, format:'jpeg', class: " pull-left profile-thumb", size: "100x100", fallback: "no_image.png"%>
                    </tr>
                    <tr>
                        <th><%= @user.name %></th>
                        <th></th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th></th>
                    </tr>
                </table>
            <div class="row">
            <% if @user.id == current_user.id %>
             <p><%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
            <% end %>
            </div>
                <h2>New book</h2>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Title</h4>
                <%= f.text_field :title, class:"book_title col-xs-12" %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Opinion</h4>
                <%= f.text_area :body, class:"book_body col-xs-12"  %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <%= f.submit "Create Book", class:"book_submit btn btn-primary col-xs-12" %>
                </div>
        <% end %>   
    </div>

app/views/books/show.html.erb
<div class="container">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:edit] %>
      <div class="edit">
        <%= flash[:edit] %>
      </div>
    <% end %>

    <div class="row">
        <div class="col-xs-3">
             <%= form_for(@book) do |f| %>
            <% if @book.errors.any? %>
            <div id="error_explanation">
            <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
                    <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <li><%= message %></li>
                <% end %>
                    </ul>
            </div>
            <% end %>
                <table class="table">
                    <tr>
                    <%= attachment_image_tag @user, :profile_image, format:'jpeg', class: " pull-left profile-thumb", size: "100x100", fallback: "no_image.png"%>
                    </tr>
                    <tr>
                        <th>name</th>
                        <th><%= @user.name %></th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th><%= @user.introduction %></th>
                    </tr>
                </table>

            <div class="row">
            <% if @user.id == current_user.id %>
              <%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
            <% else %>
              <%= link_to "",user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
            <% end %>
            </div>
                <h2>New book</h2>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Title</h4>
                <%= f.text_field :title, class:"book_title col-xs-12" %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Opinion</h4>
                <%= f.text_area :body, class:"book_body col-xs-12"  %>
                </div>

                <div class="field row" style="margin-bottom:10px;">
                <%= f.submit "Create Book", class:"book_submit btn btn-primary col-xs-12" %>
                    </div>
                <% end %>   
                </div>


        <div class="col-xs-9">
            <h2>Book detail</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <td><%= link_to(@book.user) do %>
                        <%= attachment_image_tag @book.user, :profile_image, format:'jpeg', class: " pull-left profile-thumb", size: "50x50", fallback: "no_image.png"%><br>
                        <%= @user.name %>
                        <% end %>
                        </td>
                        <td><%= @book.title%></td>
                        <td><%= @book.body %></td>
                        <% if @book.user == current_user %>
                        <td><%= link_to "Edit", edit_book_path(@book), class:"btn-sm btn-success edit_book_7842 edit_book_#{@book.id}" %></td>
                        <td>
                        <%= link_to "Destroy" , book_path(@book),class:"btn-sm btn-danger destroy_book_7842 destroy_book_#{@book.id}", method: :delete, data: {confirm: '本当に削除しますか？'} %>
                        <% end %>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
    <div class="col-xs-3 col-xs-offset-9" style="margin-left:75%;">
      <p style="font-size:13px;">CopyRight Infratop.inc</p>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-earphone" aria-hidden="true">Boockers!!</span> </h1>

    <div class="row">
        <div class="col-xs-3 col-xs-offset-9" style="margin-left:75%;">
        <p style="font-size:13px;">CopyRight Infratop.inc</p>
        </div>
    </div>

app/views/home/index.html.erb
<div class="container">
	<div class="row">
        <div class="col-md-6 col-md-offset-3">
            <% if flash[:notice] %>
            <div class="flash">
                <%= flash[:notice] %>
            <% end %>
            <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers!</strong></h1>
            <p>In<span class="glyphicon glyphicon-book"></span><strong>Bookers!</strong></p>
            <p> about varioius books!</p>

            <p><%= link_to "Log in", new_user_session_path, class: "sign_in btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
            <p><%= link_to "Sign Up", new_user_registration_path, class: "sign_up btn btn-success col-xs-10 col-xs-offset-1 sign_up"%></p>
			</div>
	</div>
    <div class="row">
        <div class="col-xs-3 col-xs-offset-9" style="margin-left:75%;">
        <p style="font-size:13px;">CopyRight Infratop.inc</p>
        </div>
    </div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav  class="navbar navbar-dark bg-dark " style="background-color:#222;margin-bottom:0px;">
    <div class="container ">
      <nav class="nav navbar-nav navbar-lett ">
        <p class="text-white" style="font-size: 20px; padding-top:10px; color:white;">Bookers</p>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
           <li>
           <%= link_to user_path(current_user.id), class:"home glyphicon glyphicon-home home", style:"padding-top:15px; padding-bottom:15px; color:#9d9d9d; font-size:13px;" do %>  
           Home   
           <% end %>
          </li>
          <li>
           <%= link_to users_path, class:"users glyphicon glyphicon-user users", style:"padding-top:15px; padding-bottom:15px; color:#9d9d9d; font-size:13px;" do %>  
           Users   
           <% end %>
          </li>
          <li>
           <%= link_to books_path, class:"books glyphicon glyphicon-book books", style:"padding-top:15px; padding-bottom:15px; color:#9d9d9d; font-size:13px;"  do %>  
           Books   
           <% end %>
          </li>
          <li>
           <%= link_to destroy_user_session_path, class:"logout glyphicon glyphicon-log-out logout", style:"padding-top:15px; padding-bottom:15px; color:#9d9d9d; font-size:13px;" , :method => :delete do  %>  
           logout   
           <% end %>
          </li>
        <% else %>
           <li>
           <%= link_to root_path, class:"home glyphicon glyphicon-home home", style:"padding-top:15px; padding-bottom:15px; color:#9d9d9d; font-size:13px;" do %>  
           Home  
           <% end %>
          </li>
          <li>
          <%= link_to home_about_path, class:"about glyphicon glyphicon-link about", style:"padding-top:15px; padding-bottom:15px; color:#9d9d9d; font-size:13px;" do %>  
           About   
           <% end %>
          </li>
          <li>
           <%= link_to new_user_registration_path, class:"sign_up glyphicon glyphicon-edit sign_up", style:"padding-top:15px; padding-bottom:15px; color:#9d9d9d; font-size:13px;" do %>  
           sign up  
           <% end %>
          </li>
          <li>
           <%= link_to new_user_session_path, class:"sign_in glyphicon glyphicon-log-in sign_in", style:"padding-top:15px; padding-bottom:15px; color:#9d9d9d; font-size:13px;" do %>  
           login   
           <% end %>
          </li>
        <% end %>  
        </ul>
      </nav>
    </div>
    </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <div class="row">
        <div class="col-xs-3">
        <h2>User info</h2>
            <% if @user.errors.any? %>
            <div id="error_explanation">
            <h2 style="font-size:24px; color:red;"><%= pluralize(@user.errors.count, "error" )%>  prohibited this obj from being saved:</h2>
                    <ul>
                    <% @user.errors.full_messages.each do |message| %>
                    <li style="font-size:13px; color:red;"><%= message %></li>
                <% end %>
                    </ul>
            </div>
            <% end %>
            <%= form_for(@user) do |f| %>
            <div class="field" style="margin-bottom: 10px;">
            <label class="control-label " for="inputEmail">Name</label>
             <%= f.text_field :name, autofocus: true, class:"name", id:"inputEmail"%>      
            </div>
            <div class="field" style="margin-bottom: 10px;">
            <label class="control-label " for="inputEmail">Image</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
            </div>
            <div class="field" style="margin-bottom: 10px;">
            <label class="control-label " for="inputEmail">Introduction</label>
            <%= f.text_area :introduction, autofocus: true, class:"introduction", id:"inputEmail"%> 
            </div>
            <div class="action" style="margin-bottom: 10px;">
             <%= f.submit "Update User", class:"#" %>
            </div>
            <% end %>
        </div>


        <div class="col-xs-9">
        </div>
 <div class="row">
    <div class="col-xs-3 col-xs-offset-9" style="margin-left:75%;">
      <p style="font-size:13px;">CopyRight Infratop.inc</p>
    </div>
    </div>       
</div>

app/views/users/index.html.erb
<div class="container">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <div class="row">
        <div class="col-xs-3">
           <%= form_for(@book) do |f| %>
            <% if @book.errors.any? %>
            <div id="error_explanation">
            <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
                    <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <li><%= message %></li>
                <% end %>
                    </ul>
            </div>
            <% end %>
           
            <h2>User info</h2>
                <table class="table">
                    <tr>
                    <%= attachment_image_tag current_user, :profile_image, format:'jpeg', class: " pull-left profile-thumb", size: "100x100", fallback: "no_image.png"%>
                    </tr>
                    <tr>
                        <th>name</th>
                        <th><%= current_user.name %></th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th><%= current_user.introduction %></th>
                    </tr>
                </table>
            <div class="row">
            <% if current_user.id %>
             <p><%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{current_user.id}" %></p>
            <% end %>
            </div>
                <h2>New book</h2>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Title</h4>
                <%= f.text_field :title, class:"book_title col-xs-12" %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Opinion</h4>
                <%= f.text_area :body, class:"book_body col-xs-12"  %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <%= f.submit "Create Book", class:"book_submit btn btn-primary col-xs-12" %>
                </div>
        <% end %>   
        
        </div>


        <div class="col-xs-9">
            <h2>Users</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>image</th>
                        <th>name</th>
                        <th></th>
                    </tr>
                </thead>
                <% @users.each do |user| %>
                <thead>
                    <tr>
                        <th><%= attachment_image_tag user, :profile_image, format:'jpeg', class: " pull-left profile-thumb", size: "50x50", fallback: "no_image.png"%></th>
                        <th><%= user.name %> </th>
                        <th><%= link_to "show", user_path(user.id), class:"user_#{user.id}"%></th>
                    </tr>
                </thead>
                <% end %>
            </table>
        </div>
    </div>
    <div class="row">
    <div class="col-xs-3 col-xs-offset-9" style="margin-left:75%;">
      <p style="font-size:13px;">CopyRight Infratop.inc</p>
    </div>
    </div>
    
</div>

app/views/users/show.html.erb
<div class="container">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="row">
        <div class="col-xs-3">
        <%= form_for(@book) do |f| %>
            <% if @book.errors.any? %>
            <div id="error_explanation">
            <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
                    <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <li><%= message %></li>
                <% end %>
                    </ul>
            </div>
            <% end %>
            <div>
            <h2>User info</h2>
                <table class="table">
                    <tr>
                    <%= attachment_image_tag @user, :profile_image, format:'jpeg', class: " pull-left profile-thumb", size: "100x100", fallback: "no_image.png"%>
                    </tr>
                    <tr>
                        <th>name</th>
                        <th><%= @user.name %></th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th><%= @user.introduction %></th>
                    </tr>
                </table>
            <div class="row">
            <% if @user.id == current_user.id %>
              <%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
            <% else %>
              <%= link_to "",user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
            <% end %>
            </div>

                <h2>New book</h2>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Title</h4>
                <%= f.text_field :title, class:"book_title col-xs-12" %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <h4 style="margin-top:0; margin-bottom:5px; font-size:14px;">Opinion</h4>
                <%= f.text_area :body, class:"book_body col-xs-12"  %>
                </div>
                <div class="field row" style="margin-bottom:10px;">
                <%= f.submit "Create Book", class:"book_submit btn btn-primary col-xs-12" %>
                </div>
        <% end %>   
        </div>

        </div>


        <div class="col-xs-9">
            <h2>Books </h2>
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                    </tr>
                </thead>
                <% @books.each do |book| %>
                <thead>
                    <tr>
                        <th><%= attachment_image_tag @user, :profile_image, format:'jpeg', class: " pull-left profile-thumb", size: "50x50", fallback: "no_image.png"%></th>
                        <th>
                        <%= link_to book_path(book.id), class:"book_#{book.id}" do %>
                        <%= book.title %>
                         <% end %>
                        </th>
                        <th><%= book.body %></th>
                    </tr>
                </thead>
                <% end %>
            </table>
        </div>
    </div>
    <div class="row">
    <div class="col-xs-3 col-xs-offset-9" style="margin-left:75%;">
      <p style="font-size:13px;">CopyRight Infratop.inc</p>
    </div>
    </div>
</div>